mcelog: Improve cache-error-trigger script
Two issues:

1) The script would attempt to take all CPUs offline for an L3 cache
error on a single socket system.
2) Many users don't want any CPUs taken offline because of the reduced
system performance.

Make the default to just log the affected CPUs. But make it simple to
enable offline for users that still want that.

If offline is enabled, sanity check AFFECTED_CPUS does not refer to
all online CPUs.

Signed-off-by: Tony Luck <tony.luck@intel.com>

diff --git a/triggers/cache-error-trigger b/triggers/cache-error-trigger
--- a/triggers/cache-error-trigger
+++ b/triggers/cache-error-trigger
@@ -15,9 +15,25 @@
 # this can be changed in mcelog.conf
 
 #
+# Change "DO_OFFLINE" to "1" if you want to
 # offline the CPUs sharing the affected cache
 #
+DO_OFFLINE=0
+
 EXIT=0
+
+logger -s -p daemon.crit -t mcelog "Level $LEVEL cache error threshold affects CPUs: $AFFECTED_CPUS"
+
+if [ $DO_OFFLINE = 0 ]
+then
+	exit $EXIT
+fi
+
+if [ $(echo $AFFECTED_CPUS | wc -w) -ge $(grep -c ^processor /proc/cpuinfo) ]
+then
+	logger -s -p daemon.crit -t mcelog "Too many CPUs affected by cache error threshold to offline"
+	exit $EXIT
+fi
 
 for i in $AFFECTED_CPUS ; do
 	logger -s -p daemon.crit -t mcelog "Offlining CPU $i due to cache error threshold"
